### ISSUE TITLE
Notification not working on android

### ISSUE THREAD

**Issue by KoenBaak** [kivy/plyer#533]
I have the following minimal app:

`
from kivy.app import App
from kivy.uix.button import Button
import plyer

class MyApp(App):
    
    def build(self):
        return Button(text="click me", on_release=lambda x: self.show_notification())
        
    def show_notification(self):
        plyer.notification.notify(title='test', message="Notification using plyer")

MyApp().run()
`

which works fine on linux. However, when clicking the button on android, the app crashes. log:

`01-07 16:06:52.815 12099 12138 I python  :  Traceback (most recent call last):
01-07 16:06:52.815 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/app/main.py", line 13, in <module>
01-07 16:06:52.816 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/app.py", line 855, in run
01-07 16:06:52.816 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 504, in runTouchApp
01-07 16:06:52.816 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 747, in mainloop
01-07 16:06:52.816 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/core/window/window_sdl2.py", line 479, in _mainloop
01-07 16:06:52.817 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 342, in idle
01-07 16:06:52.817 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 327, in dispatch_input
01-07 16:06:52.817 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/base.py", line 293, in post_dispatch_input
01-07 16:06:52.817 12099 12138 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
01-07 16:06:52.818 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/uix/behaviors/button.py", line 179, in on_touch_up
01-07 16:06:52.818 12099 12138 I python  :    File "kivy/_event.pyx", line 703, in kivy._event.EventDispatcher.dispatch
01-07 16:06:52.818 12099 12138 I python  :    File "kivy/_event.pyx", line 1214, in kivy._event.EventObservers.dispatch
01-07 16:06:52.818 12099 12138 I python  :    File "kivy/_event.pyx", line 1138, in kivy._event.EventObservers._dispatch
01-07 16:06:52.819 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/app/main.py", line 7, in <lambda>
01-07 16:06:52.819 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/app/main.py", line 10, in show_notification
01-07 16:06:52.819 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/plyer/facades/notification.py", line 84, in notify
01-07 16:06:52.819 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/plyer/platforms/android/notification.py", line 177, in _notify
01-07 16:06:52.820 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/plyer/platforms/android/notification.py", line 126, in _build_notification
01-07 16:06:52.820 12099 12138 I python  :    File "/home/......some...path.....//.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/plyer/platforms/android/notification.py", line 74, in _build_notification_channel
01-07 16:06:52.820 12099 12138 I python  :  AttributeError: 'NoneType' object has no attribute 'createNotificationChannel'
01-07 16:06:52.820 12099 12138 I python  : Python for android ended.`

**Comment by Jonatanjrss** [comment]
I generated an apk through your code and got success. I used python 3.7.4, buildozer 0.39, Cython 0.28.6 e kivy 1.11.1.

**Comment by Franccisco** [comment]
@KoenBaak @Jonatanjrss which Android version?

**Comment by Jonatanjrss** [comment]
My android version is 7.1.2

**Comment by KoenBaak** [comment]
I am working with python 3.6.9, buildozer 1.0, cython 0.29.14, kivy 1.11.1 and android 9. I tried it again in a fresh virtual environment with buildozer 0.39 but I could not compile for some reason...

**Comment by Jonatanjrss** [comment]
@KoenBaak

Use Cython 0.28.6, buildozer 0.39 and kivy 1.11.0

See my script: https://gitlab.com/jonatanjrss/teste/tree/devlopment

Then I will test more up-to-date versions of Cython, buildozer and kivy that work.

I recommend that you use my script. It works. But read README.md first.

**Comment by Franccisco** [comment]
@Jonatanjrss did you test it with the same android version that @KoenBaak said?

@KoenBaak take a look at this: https://github.com/kivy/plyer/issues/504

**Comment by Jonatanjrss** [comment]
@Franccisco. I only tested with my android version 7.1.2

**Comment by Robinosius** [comment]
I've got the exact same issue on Android 10
